<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\BeritaController;
use App\Http\Controllers\MainController;
use App\Http\Controllers\MasterController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\DokumenController;
use App\Http\Controllers\BagianController;
use App\Http\Controllers\AgendaController;
use App\Http\Controllers\ApbdController;
use App\Http\Controllers\SignageController;
use App\Http\Controllers\WbsController;

Route::get('/', [MainController::class,'index']);
Route::get('/allBerita',[MainController::class,'allBerita']);
Route::get('/detailBerita/{id}',[MainController::class,'detailBerita']);
Route::get('/dok/{id}',[MainController::class,'dok']);
Route::get('/login',[AuthController::class,'login'])->name('login');
Route::post('/logout',[AuthController::class,'logout']);
Route::post('/authenticate',[AuthController::class,'authenticate']);
Route::get('/dashboard',[MainController::class,'dashboard'])->middleware('auth');
Route::resource('/slider',SliderController::class)->middleware('auth');
Route::resource('/berita',BeritaController::class)->middleware('auth');
Route::resource('/master',MasterController::class)->middleware('auth');
Route::resource('/kategori',KategoriController::class)->middleware('auth');
Route::resource('/dokumen',DokumenController::class)->middleware('auth');
Route::resource('/bagian',BagianController::class)->middleware('auth');
Route::resource('/agenda',AgendaController::class)->middleware('auth');
Route::resource('/apbd',ApbdController::class)->middleware('auth');
Route::resource('/wbs',WbsController::class)->middleware('auth');
Route::put('/wbs/verif/{id}',[WbsController::class,'verif'])->middleware('auth')->name('wbs.verif');
Route::post('/apbd/upload',[ApbdController::class,'upload'])->name('apbd.upload');
Route::post('/apbd/updateData',[ApbdController::class,'updateData'])->name('apbd.updateData');
Route::get('/signage',[SignageController::class,'index'])->name('signage');
Route::get('/whistle_blowing',[MainController::class,'whistle_blowing'])->name('whistle_blowing');
Route::get('/formWbs',[MainController::class,'formWbs'])->name('formWbs');
Route::post('/kirimWbs',[MainController::class,'kirimWbs'])->name('kirimWbs');
Route::get('/messageWbs',[MainController::class,'messageWbs'])->name('messageWbs');